---
- name: Manage Untagged Instances
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - role: manage-untagged-instances
      aws_region: us-west-2
    - role: manage-untagged-instances
      aws_region: us-west-1
