---
- name: Build a list of instances
  ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
  register: aws_instances

- name: Count aws_instances
  debug:
    var: aws_instances | length
  when: aws_instances.instances | length > 0

- name: Filter instances based on AlwaysUp:NO tag or missing tag
  set_fact:
    instance_ids: "{{ aws_instances | json_query(aws_query) }}"
  vars:
    aws_query: "instances[?tags.AlwaysUp!='True' && 'true' && 'yes' && 'Yes'].instance_id"
  when: aws_instances.instances | length > 0

- name: Log instance_ids
  debug:
    var: instance_ids
  when: instance_ids | length > 0

- name: Assign missing AlwaysUp tag
  ec2_tag:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    resource: "{{ item }}"
    state: present
    tags:
      AlwaysUp: False
  with_items: "{{ instance_ids }}"
  when: instance_ids | length > 0

- name: Stop the AlwaysUp:NO instances
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    instance_ids: "{{ instance_ids }}"
    state: stopped
    wait: False
  when: instance_ids | length > 0
